#!/usr/bin/env python
"""Run official Text2CAD inference with a prepared config file."""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--text2cad-root", type=Path, required=True, help="Path to the official Text2CAD checkout.")
    parser.add_argument("--config", type=Path, required=True, help="Config generated by prepare_text2cad_inputs.py.")
    parser.add_argument("--python", default=sys.executable, help="Python executable for the Text2CAD environment.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    text2cad_root = args.text2cad_root.resolve()
    config_path = args.config.resolve()
    inference_script = text2cad_root / "Cad_VLM" / "test_user_input.py"

    if not inference_script.exists():
        raise FileNotFoundError(f"Missing official Text2CAD inference script: {inference_script}")
    if not config_path.exists():
        raise FileNotFoundError(f"Missing prepared config: {config_path}")

    command = [
        args.python,
        str(inference_script),
        "--config_path",
        str(config_path),
    ]
    subprocess.run(command, cwd=str(inference_script.parent), check=True)


if __name__ == "__main__":
    main()
